#!/usr/bin/env python3
"""Generate new coverage test tables (Python reference via verify_smoke ref_eval)."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path
from typing import Optional

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))

from verify_smoke_expected_vs_python import ref_eval, ref_format, try_reference  # noqa: E402

EXE_CPP = ROOT / "cpp" / "MathParserTests.exe"
EXE_BAS = ROOT / "tools" / "NegBandProbe.exe"


def esc_bas(s: str) -> str:
    return s.replace('"', '""')


def esc_cpp(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def ref_expect(expr: str, *, mode: str = "real") -> tuple[str, bool, str]:
    """Return (expect_or_err, is_err, err_substr). Prefer Python/reference."""
    try:
        v, err = try_reference(expr, mode=mode)
        if err:
            return err, True, err
        return ref_format(v, mode=mode), False, ""
    except Exception as ex:
        return str(ex), True, str(ex)


def expect_from_reference_first(expr: str, *, complex_mode: bool = False) -> tuple[str, bool, bool, str]:
    """Return (expect_or_err, is_ok, is_err, err_substr)."""
    mode = "complex" if complex_mode else "real"
    exp, is_err, err = ref_expect(expr, mode=mode)
    if is_err:
        return exp, False, True, err
    return exp, True, False, ""


def parser_result(expr: str, *, complex_mode: bool = False) -> tuple[str, bool]:
    if EXE_BAS.is_file():
        bas_args = [str(EXE_BAS)]
        if complex_mode:
            bas_args.append("--complex")
        bas_args.append(expr)
        try:
            bas_proc = subprocess.run(bas_args, capture_output=True, text=True, cwd=ROOT, timeout=30)
            bas_out = (bas_proc.stdout or "").strip()
            if bas_proc.returncode == 0 and bas_out:
                return bas_out, True
            if bas_proc.returncode != 0 and bas_out.startswith("ERROR:"):
                return bas_out[6:].strip(), False
        except (OSError, subprocess.TimeoutExpired):
            pass
    if not EXE_CPP.is_file():
        return "", False
    args = [str(EXE_CPP), "--eval"]
    if complex_mode:
        args.append("--complex")
    args.append(expr)
    proc = subprocess.run(args, capture_output=True, text=True, cwd=ROOT / "cpp", timeout=30)
    out = (proc.stdout or "").strip()
    if proc.returncode != 0:
        if out.startswith("ERROR:"):
            return out[6:].strip(), False
        return out or "error", False
    return out, True


def write_float_magnitude() -> None:
    literals = [
        "1.123e+20",
        "-1.123e+20",
        "1.123e-20",
        "-1.123e-20",
        "1.123e+197",
        "1.123e-197",
        "0.0",
        "-0.0",
    ]
    probes = [
        ("add0", "{v}+0"),
        ("mul2", "{v}*2"),
        ("div2", "{v}/2"),
        ("abs", "abs({v})"),
        ("sign", "sign({v})"),
        ("ln", "ln({v})"),
        ("eq", "{v}=={v}"),
    ]
    rows: list[tuple[str, str, str, bool, str]] = []
    for v in literals:
        for pid, tmpl in probes:
            expr = tmpl.format(v=v)
            label = f"floatmag/{v}/{pid}"
            expect, is_err, err = ref_expect(expr, mode="real")
            if is_err and pid == "ln":
                pr, okp = parser_result(expr)
                if okp:
                    rows.append((label, expr, pr, False, ""))
                    continue
            if is_err:
                rows.append((label, expr, "", True, err[:80]))
                continue
            rows.append((label, expr, expect, False, ""))

    bas = ROOT / "tools" / "float_magnitude_cases_generated.bas"
    cpp = ROOT / "tools" / "float_magnitude_cases_generated.cpp.inc"
    n = len(rows)
    with bas.open("w", encoding="utf-8", newline="\n") as f:
        f.write("' AUTO-GENERATED by tools/gen_new_coverage_tests.py\n\n")
        f.write(f"const FLOAT_MAG_COUNT = {n}\n")
        for name in ("floatMagLabel", "floatMagExpr", "floatMagExpect", "floatMagErr", "floatMagIsErr"):
            f.write(f"dim shared {name}(1 to FLOAT_MAG_COUNT) as ")
            f.write("Boolean\n" if name == "floatMagIsErr" else "String\n")
        for i, (label, expr, expect, is_err, err) in enumerate(rows, 1):
            f.write(f'floatMagLabel({i}) = "{esc_bas(label)}"\n')
            f.write(f'floatMagExpr({i}) = "{esc_bas(expr)}"\n')
            if is_err:
                f.write(f'floatMagErr({i}) = "{esc_bas(err)}"\n')
                f.write(f"floatMagIsErr({i}) = TRUE\n")
            else:
                f.write(f'floatMagExpect({i}) = "{esc_bas(expect)}"\n')
                f.write(f"floatMagIsErr({i}) = FALSE\n")
        f.write("\n")
    with cpp.open("w", encoding="utf-8", newline="\n") as f:
        f.write("// AUTO-GENERATED by tools/gen_new_coverage_tests.py\n")
        for label, expr, expect, is_err, err in rows:
            el = esc_cpp(expr)
            if is_err:
                f.write(f'    {{"{esc_cpp(label)}", "{el}", nullptr, "{esc_cpp(err)}"}},\n')
            else:
                f.write(f'    {{"{esc_cpp(label)}", "{el}", "{esc_cpp(expect)}", nullptr}},\n')
    print(f"float magnitude: {n} rows -> {bas.name}")


def naninf_cases() -> list[tuple[str, str, Optional[str], Optional[str]]]:
    """(name, expr, expected, err_contains) — literals instead of const x."""
    t: list[tuple[str, str, Optional[str], Optional[str]]] = [
        ("naninf/quiet NaN dec identity", "nan+0", "nan", None),
        ("naninf/+inf dec identity", "inf+0", "inf", None),
        ("naninf/-inf dec identity", "-inf+0", "-inf", None),
        ("naninf/inf plus finite", "inf+1", "inf", None),
        ("naninf/-inf minus finite", "-inf-1", "-inf", None),
        ("naninf/nan plus finite stays nan", "nan+1", "nan", None),
        ("naninf/abs -inf", "abs(-inf)", "inf", None),
        ("naninf/abs nan", "abs(nan)", "nan", None),
        ("naninf/sign +inf", "sign(inf)", "1", None),
        ("naninf/sign -inf", "sign(-inf)", "-1", None),
        ("naninf/sign nan", "sign(nan)", "0", None),
        ("naninf/ln nan", "ln(nan)", "nan", None),
        ("naninf/ln +inf", "ln(inf)", "inf", None),
        ("naninf/ln zero to -inf", "ln(0)", "-inf", None),
        ("naninf/sqrt nan", "sqrt(nan)", "nan", None),
        ("naninf/sin +inf", "sin(inf)", None, "numeric error in sin()"),
        ("naninf/frac +inf", "frac(inf)", "nan", None),
        ("naninf/frac nan", "frac(nan)", "nan", None),
        ("naninf/hex NaN preserved", "hex(nan)", "nan", None),
        ("naninf/hex +inf preserved", "hex(inf)", "inf", None),
        ("naninf/oct -inf preserved", "oct(-inf)", "-inf", None),
        ("naninf/uhex +inf preserved", "uhex(inf)", "inf", None),
        ("naninf/mod NaN rejects", "mod(nan,3)", None, "mod() expects integer values"),
        ("naninf/mod +inf rejects", "mod(inf,3)", None, "mod() expects integer values"),
        ("naninf/gcd NaN rejects", "gcd(nan,1)", None, "gcd() expects integer values"),
        ("naninf/bitand NaN rejects", "nan&1", None, "bitwise operands must be integer values"),
        ("naninf/bitand +inf rejects", "inf&1", None, "bitwise operands must be integer values"),
        ("naninf/sum with +inf rejects", "sum(1,inf)", "inf", None),
        ("naninf/not NaN is true (NaN is falsy)", "not nan", "1", None),
        ("naninf/not +inf is false", "not inf", "0", None),
        ("naninf/NaN and 1", "nan&&1", "0", None),
        ("naninf/NaN or 1", "nan||1", "1", None),
        ("naninf/NaN == NaN is false (IEEE unordered)", "nan==nan", "0", None),
        ("naninf/nan==nan literal false", "nan==nan", "0", None),
        ("naninf/nan!=nan literal true", "nan!=nan", "1", None),
        ("naninf/nan<>nan literal true", "nan<>nan", "1", None),
        ("naninf/nan<nan literal false", "nan<nan", "0", None),
        ("naninf/nan>nan literal false", "nan>nan", "0", None),
        ("naninf/nan<=nan literal false", "nan<=nan", "0", None),
        ("naninf/nan>=nan literal false", "nan>=nan", "0", None),
        ("naninf/+inf == +inf", "inf==inf", "1", None),
        ("naninf/array arg sum with +inf", "sum((inf,2,3))", "inf", None),
        (
            "naninf/sort orders NaN before infinities and numbers",
            "sort(0xFFFFFFFFFFFFFFFF,nan,0x7FFFFFFFFFFFFFFF);hex",
            "(nan,0x7FFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF)",
            None,
        ),
        ("naninf/array arg mod rejects +inf", "mod((inf,2),3)", None, "mod() expects integer values"),
        ("naninf/2arg function hypot(+inf,3)", "hypot(inf,3)", "inf", None),
        ("naninf/3arg function clamp(+inf,0,7)", "clamp(inf,0,7)", "7", None),
        ("naninf/udf 1 arg with +inf", "f(a)=a+1; f(inf)", "inf", None),
        ("naninf/udf 2 args with +inf", "f(a,b)=a*b; f(inf,2)", "inf", None),
        ("naninf/operator arithmetic multiply", "inf*2", "inf", None),
        ("naninf/operator bitwise or rejects +inf", "inf|1", None, "bitwise operands must be integer values"),
        ("naninf/operator logical and", "inf&&0", "0", None),
        ("naninf/operator comparison greater", "inf>1", "1", None),
        ("naninf/variadic sum with +inf", "sum(1,2,inf)", "inf", None),
        ("naninf/variadic max with +inf", "max(1,2,inf)", "inf", None),
        ("naninf/variadic avg with +inf", "avg(1,inf,3)", "inf", None),
        ("naninf/operator compare +inf == +inf", "inf==inf", "1", None),
        ("naninf/array arg sum with -inf", "sum((-inf,2,3))", "-inf", None),
        ("naninf/array arg mod rejects -inf", "mod((-inf,2),3)", None, "mod() expects integer values"),
        ("naninf/2arg function hypot(-inf,3)", "hypot(-inf,3)", "inf", None),
        ("naninf/3arg function clamp(-inf,0,7)", "clamp(-inf,0,7)", "0", None),
        ("naninf/udf 1 arg with -inf", "f(a)=a+1; f(-inf)", "-inf", None),
        ("naninf/udf 2 args with -inf", "f(a,b)=a*b; f(-inf,2)", "-inf", None),
        ("naninf/operator arithmetic multiply -inf", "-inf*2", "-inf", None),
        ("naninf/operator bitwise or rejects -inf", "-inf|1", None, "bitwise operands must be integer values"),
        ("naninf/operator logical and -inf", "-inf&&0", "0", None),
        ("naninf/operator comparison -inf not greater than 1", "-inf>1", "0", None),
        ("naninf/variadic sum with -inf", "sum(1,2,-inf)", "-inf", None),
        ("naninf/variadic max with -inf", "max(1,2,-inf)", "2", None),
        ("naninf/variadic avg with -inf", "avg(1,-inf,3)", "-inf", None),
        ("naninf/operator compare -inf == -inf", "-inf==-inf", "1", None),
        ("naninf/** inf**2", "inf**2", "inf", None),
        ("naninf/** 2**inf", "2**inf", "inf", None),
        ("naninf/** inf**inf", "inf**inf", "inf", None),
        ("naninf/pow(inf,2)", "pow(inf,2)", "inf", None),
        ("naninf/pow(2,inf)", "pow(2,inf)", "inf", None),
        ("naninf/pow(inf,inf)", "pow(inf,inf)", "inf", None),
        ("naninf/atan2(+inf,1)", "atan2(inf,1)", "1.570796326794897", None),
        ("naninf/atan2(-inf,1)", "atan2(-inf,1)", "-1.570796326794897", None),
        ("naninf/atan2(1,-inf)", "atan2(1,-inf)", "3.141592653589793", None),
        ("naninf/sin -inf", "sin(-inf)", None, "numeric error in sin()"),
        ("naninf/int accepts -inf", "int(-inf)", "-inf", None),
        ("naninf/int accepts inf", "int(inf)", "inf", None),
        ("naninf/int accepts -nan", "int(-nan)", "nan", None),
        ("naninf/int accepts nan", "int(nan)", "nan", None),
        ("naninf/ceil accepts -inf", "ceil(-inf)", "-inf", None),
        ("naninf/floor accepts inf", "floor(inf)", "inf", None),
        ("naninf/round accepts -nan", "round(-nan)", "nan", None),
        ("naninf/trunc accepts nan", "trunc(nan)", "nan", None),
    ]
    # Second sort batch inside one C++ case — separate rows for Basic
    t.append(
        (
            "naninf/sort -5 nan 3 -inf inf 0",
            "sort(-5,nan,3,-inf,inf,0)",
            "(nan,-inf,-5,0,3,inf)",
            None,
        )
    )
    t.append(
        (
            "naninf/sort nan inf 2 -inf nan -2",
            "sort(nan,inf,2,-inf,nan,-2)",
            "(nan,nan,-inf,-2,2,inf)",
            None,
        )
    )
    t.append(
        (
            "naninf/sorted nan -3 4 inf -inf",
            "sorted((nan,-3,4,inf,-inf))",
            "(nan,-inf,-3,4,inf)",
            None,
        )
    )
    return t


def write_naninf_mirror() -> None:
    cases = naninf_cases()
    bas = ROOT / "tools" / "naninf_mirror_generated.bas"
    n = len(cases)
    with bas.open("w", encoding="utf-8", newline="\n") as f:
        f.write("' AUTO-GENERATED by tools/gen_new_coverage_tests.py\n\n")
        f.write(f"const NANINF_MIRROR_COUNT = {n}\n")
        for p in ("naninfLabel", "naninfExpr", "naninfExpect", "naninfErr", "naninfIsErr"):
            f.write(f"dim shared {p}(1 to NANINF_MIRROR_COUNT) as ")
            f.write("Boolean\n" if p == "naninfIsErr" else "String\n")
        for i, (name, expr, expect, err) in enumerate(cases, 1):
            f.write(f'naninfLabel({i}) = "{esc_bas(name)}"\n')
            f.write(f'naninfExpr({i}) = "{esc_bas(expr)}"\n')
            if err:
                f.write(f'naninfErr({i}) = "{esc_bas(err)}"\n')
                f.write(f"naninfIsErr({i}) = TRUE\n")
            else:
                f.write(f'naninfExpect({i}) = "{esc_bas(expect or "")}"\n')
                f.write(f"naninfIsErr({i}) = FALSE\n")
        f.write("\n")
    print(f"naninf mirror: {n} rows -> {bas.name}")


TIME_EXPECT_OVERRIDES: dict[str, str] = {
    # verify_smoke tuple*time broadcast differs from Smart Math duration semantics
    "seconds((1:00,0:30)*2)": "(120,60)",
    "days((0:30,1:00)+0:30)": "(0.0006944444444444444,0.0010416666666666666)",
    "hours((1:00,0:30)*60)": "(1,0.5)",
    "days((1:00,0:30)*2)": "(0.001388888888888888,0.0006944444444444444)",
}


def main_smoke_time_rows() -> list[tuple[str, str, Optional[str], Optional[str]]]:
    """(expr, expected, err_contains) for main tests table."""
    rows = [
        ("hours((1:00,0:30)*60)", None, None),
        ("(1:45, 2)", None, "time values cannot be mixed with non-time values"),
        ("1/1:00", None, "incompatible operands"),
        ("1:00 + 5", None, None),
        ("999d", None, None),
        ("999d+1d", None, None),
        ("milliseconds(999d)", None, None),
        ("seconds((1:00,0:30)*2)", None, None),
        ("days((0:30,1:00)+0:30)", None, None),
        ("days((1:00,0:30)*2)", None, None),
        ("1:00**2", None, "incompatible operands"),
        ("1:00%2", None, "modulo operands must be integer values"),
        ("0:30**2", None, "incompatible operands"),
    ]
    out = []
    for expr, _e, err in rows:
        if err:
            out.append((expr, None, err))
            continue
        if expr in TIME_EXPECT_OVERRIDES:
            out.append((expr, TIME_EXPECT_OVERRIDES[expr], None))
            continue
        v, er = try_reference(expr, mode="time")
        if er:
            out.append((expr, None, er))
        else:
            out.append((expr, ref_format(v, mode="time"), None))
    return out


def write_smoke_parity_append() -> None:
    rows = main_smoke_time_rows()
    # Real scalar parity (decimal) for max uint64 product edge.
    rows.append(("product(18446744073709551615,1)", "18446744073709551615", None))

    append_bas = ROOT / "tools" / "smoke_parity_append_generated.bas"
    append_cpp = ROOT / "tools" / "smoke_parity_append_generated.cpp.inc"
    with append_bas.open("w", encoding="utf-8", newline="\n") as f:
        f.write("' AUTO-GENERATED append rows for main tests() — indices assigned in SmokeTest.\n")
        f.write(f"const SMOKE_APPEND_COUNT = {len(rows)}\n")
        f.write("dim shared smokeAppendExpr(1 to SMOKE_APPEND_COUNT) as String\n")
        f.write("dim shared smokeAppendExpected(1 to SMOKE_APPEND_COUNT) as String\n")
        f.write("dim shared smokeAppendErr(1 to SMOKE_APPEND_COUNT) as String\n")
        f.write("dim shared smokeAppendIsErr(1 to SMOKE_APPEND_COUNT) as Boolean\n")
        for i, (expr, expect, err) in enumerate(rows, 1):
            f.write(f'smokeAppendExpr({i}) = "{esc_bas(expr)}"\n')
            if err:
                f.write(f'smokeAppendErr({i}) = "{esc_bas(err)}"\n')
                f.write(f"smokeAppendIsErr({i}) = TRUE\n")
            else:
                f.write(f'smokeAppendExpected({i}) = "{esc_bas(expect or "")}"\n')
                f.write(f"smokeAppendIsErr({i}) = FALSE\n")
    with append_cpp.open("w", encoding="utf-8", newline="\n") as f:
        for expr, expect, err in rows:
            el = esc_cpp(expr)
            if err:
                f.write(
                    f'    {{ParityBasicCase::Kind::ErrorContains, "{el}", "{esc_cpp(err)}"}} ,\n'
                )
            else:
                f.write(
                    f'    {{ParityBasicCase::Kind::Expected, "{el}", "{esc_cpp(expect or "")}"}} ,\n'
                )
    print(f"smoke append: {len(rows)} rows")


def write_complex_coverage() -> None:
    rows: list[tuple[str, str, Optional[str], Optional[str], bool]] = []

    def add_probe(label: str, expr: str) -> None:
        """Prefer Python/reference for successes; fall back to parser eval."""
        exp, ok, _is_err, _err = expect_from_reference_first(expr, complex_mode=True)
        if ok:
            rows.append((label, expr, exp, None, False))
            return
        pr, pok = parser_result(expr, complex_mode=True)
        if pok:
            rows.append((label, expr, pr, None, False))
            return
        rows.append((label, expr, None, pr or "error", True))

    def add_forbid_probe(label: str, expr: str) -> None:
        """Forbidden ops: lock error text to parser (Basic smoke), not Python exceptions."""
        pr, pok = parser_result(expr, complex_mode=True)
        if pok:
            rows.append((label, expr, pr, None, False))
            return
        rows.append((label, expr, None, pr or "error", True))

    def add_probe_parser_first(label: str, expr: str) -> None:
        pr, pok = parser_result(expr, complex_mode=True)
        if pok:
            rows.append((label, expr, pr, None, False))
            return
        exp, _ok, _is_err, err = expect_from_reference_first(expr, complex_mode=True)
        if _ok:
            rows.append((label, expr, exp, None, False))
            return
        rows.append((label, expr, None, pr or err or "error", True))

    # C5 doc utilities (lock to parser format for cross-platform ULP parity)
    for expr in ("sign(1+2i)", "(1+2i)/abs(1+2i)", "fact(1+2i)"):
        add_probe_parser_first(f"cxdoc/{expr}", expr)

    operands = ["nan+2i", "nan+3i", "2+nan*i", "inf+2i", "nan+nan*i", "inf+nan*i", "nan*inf"]
    op_templates = [
        ("add", "{z}+1"),
        ("sub", "{z}-1"),
        ("mul", "{z}*2"),
        ("div", "{z}/2"),
        ("pow", "{z}**2"),
        ("uplus", "+({z})"),
        ("uminus", "-({z})"),
        ("eq_self", "{z}=={z}"),
        ("neq", "{z}!=1+2i"),
        ("and", "({z})&&1"),
        ("or", "({z})||0"),
        ("not", "not({z})"),
    ]
    forbidden = [
        ("pct", "({z})%3"),
        ("lt", "{z}<{z}"),
        ("shl", "{z}<<1"),
        ("band", "{z}&1"),
    ]
    for z in operands:
        for op_id, tmpl in op_templates:
            expr = tmpl.format(z=z)
            add_probe(f"cxnf/{z}/{op_id}", expr)
        for op_id, tmpl in forbidden:
            expr = tmpl.format(z=z)
            add_forbid_probe(f"cxnf/forbid/{z}/{op_id}", expr)

    add_probe("cxnf/eq_nan2i", "(nan+2i)==(nan+2i)")
    add_probe("cxnf/sortby_abs", "sortby((1+2i, 3-i), abs)")
    # Lexer/decimal exact-int preservation: lock to parser output
    add_probe_parser_first("cxlex/bare_int64min", "-9223372036854775808+1i")
    add_probe_parser_first("cxlex/paren_int64min", "(-9223372036854775808)+1i")

    bas = ROOT / "tools" / "complex_coverage_generated.bas"
    cpp = ROOT / "tools" / "complex_coverage_generated.cpp.inc"
    n = len(rows)
    with bas.open("w", encoding="utf-8", newline="\n") as f:
        f.write("' AUTO-GENERATED by tools/gen_new_coverage_tests.py\n\n")
        f.write(f"const CX_COVERAGE_COUNT = {n}\n")
        for p in ("cxCovLabel", "cxCovExpr", "cxCovExpect", "cxCovErr", "cxCovIsErr"):
            f.write(f"dim shared {p}(1 to CX_COVERAGE_COUNT) as ")
            f.write("Boolean\n" if p == "cxCovIsErr" else "String\n")
        for i, (label, expr, expect, err, is_err) in enumerate(rows, 1):
            f.write(f'cxCovLabel({i}) = "{esc_bas(label)}"\n')
            f.write(f'cxCovExpr({i}) = "{esc_bas(expr)}"\n')
            if is_err:
                f.write(f'cxCovErr({i}) = "{esc_bas(err or "")}"\n')
                f.write(f"cxCovIsErr({i}) = TRUE\n")
            else:
                f.write(f'cxCovExpect({i}) = "{esc_bas(expect or "")}"\n')
                f.write(f"cxCovIsErr({i}) = FALSE\n")
    with cpp.open("w", encoding="utf-8", newline="\n") as f:
        f.write("// AUTO-GENERATED by tools/gen_new_coverage_tests.py\n")
        for label, expr, expect, err, is_err in rows:
            el = esc_cpp(expr)
            if is_err:
                f.write(
                    f'    {{"{esc_cpp(label)}", "{el}", nullptr, "{esc_cpp(err or "")}"}},\n'
                )
            else:
                f.write(
                    f'    {{"{esc_cpp(label)}", "{el}", "{esc_cpp(expect or "")}", nullptr}},\n'
                )
    print(f"complex coverage: {n} rows -> {bas.name}")


def main() -> int:
    write_float_magnitude()
    write_naninf_mirror()
    write_smoke_parity_append()
    write_complex_coverage()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
